<?php

declare(strict_types=1);

namespace App\Libraries\Enums;

enum PermissionNameEnum: string
{
    case HEADER_SETTINGS = 'header-settings';
    case CUSTOMER_INDEX = 'customer-index';
    case CUSTOMER_CREATE = 'customer-create';
    case CUSTOMER_STORE = 'customer-store';
    case CUSTOMER_SHOW = 'customer-show';
    case CUSTOMER_EDIT = 'customer-edit';
    case CUSTOMER_UPDATE = 'customer-update';
    case CUSTOMER_DESTROY = 'customer-destroy';
    case CUSTOMER_DESTROY_GROUP = 'customer-destroy-group';
    case CUSTOMER_RESTORE = 'customer-restore';
    case CUSTOMER_RESTORE_GROUP = 'customer-restore-group';
    case STOCK_EXIT_CREATE = 'stock-exit-create';
    case STOCK_EXIT_STORE = 'stock-exit-store';
    case STOCK_EXIT_DESTROY = 'stock-exit-destroy';
    case STOCK_EXIT_DESTROY_GROUP = 'stock-exit-destroy-group';
    case STOCK_ENTRY_CREATE = 'stock-entry-create';
    case STOCK_ENTRY_SPEND = 'stock-entry-spend';
    case STOCK_ENTRY_STORE = 'stock-entry-store';
    case PRODUCT_INDEX = 'product-index';
    case PRODUCT_SHOW = 'product-show';
    case PRODUCT_CREATE = 'product-create';
    case PRODUCT_EDIT = 'product-edit';
    case PRODUCT_STORE = 'product-store';
    case PRODUCT_UPDATE = 'product-update';
    case PRODUCT_DESTROY = 'product-destroy';
    case PRODUCT_DESTROY_GROUP = 'product-destroy-group';
    case PRODUCT_RESTORE = 'product-restore';
    case PRODUCT_RESTORE_GROUP = 'product-restore-group';
    case PRODUCT_CATEGORY_INDEX = 'product-category-index';
    case PRODUCT_CATEGORY_SHOW = 'product-category-show';
    case PRODUCT_CATEGORY_EDIT = 'product-category-edit';
    case PRODUCT_CATEGORY_UPDATE = 'product-category-update';
    case PRODUCT_CATEGORY_CREATE = 'product-category-create';
    case PRODUCT_CATEGORY_STORE = 'product-category-store';
    case PRODUCT_CATEGORY_DESTROY = 'product-category-destroy';
    case PRODUCT_CATEGORY_DESTROY_GROUP = 'product-category-destroy-group';
    case PRODUCT_CATEGORY_RESTORE = 'product-category-restore';
    case PRODUCT_CATEGORY_RESTORE_GROUP = 'product-category-restore-group';
    case SUPPLIER_INDEX = 'supplier-index';
    case SUPPLIER_CREATE = 'supplier-create';
    case SUPPLIER_STORE = 'supplier-store';
    case SUPPLIER_DESTROY = 'supplier-destroy';
    case SUPPLIER_DESTROY_GROUP = 'supplier-destroy-group';
    case SUPPLIER_EDIT = 'supplier-edit';
    case SUPPLIER_SHOW = 'supplier-show';
    case SUPPLIER_UPDATE = 'supplier-update';
    case SUPPLIER_RESTORE = 'supplier-restore';
    case SUPPLIER_RESTORE_GROUP = 'supplier-restore-group';
    case DISCOUNT_INDEX = 'discount-index';
    case DISCOUNT_CREATE = 'discount-create';
    case DISCOUNT_SHOW = 'discount-show';
    case DISCOUNT_EDIT = 'discount-edit';
    case DISCOUNT_STORE = 'discount-store';
    case DISCOUNT_UPDATE = 'discount-update';
    case DISCOUNT_DESTROY = 'discount-destroy';
    case DISCOUNT_DESTROY_GROUP = 'discount-destroy-group';
    case DISCOUNT_RESTORE = 'discount-restore';
    case DISCOUNT_RESTORE_GROUP = 'discount-restore-group';
    case PAYMENT_CARD_INDEX = 'payment-card-index';
    case PAYMENT_CARD_SHOW = 'payment-card-show';
    case PAYMENT_CARD_CREATE = 'payment-card-create';
    case PAYMENT_CARD_EDIT = 'payment-card-edit';
    case PAYMENT_CARD_UPDATE = 'payment-card-update';
    case PAYMENT_CARD_STORE = 'payment-card-store';
    case PAYMENT_CARD_DESTROY = 'payment-card-destroy';
    case PAYMENT_CARD_DESTROY_GROUP = 'payment-card-destroy-group';
    case PAYMENT_CARD_RESTORE = 'payment-card-restore';
    case PAYMENT_CARD_RESTORE_GROUP = 'payment-card-restore-group';
    case SALE_INDEX = 'sale-index';
    case SALE_SHOW = 'sale-show';
    case SALE_DESTROY = 'sale-destroy';
    case SALE_DESTROY_GROUP = 'sale-destroy-group';
    case EXCHANGE_INDEX = 'exchange-index';
    case LOSS_INDEX = 'loss-index';
}
